### ISSUE TITLE
Don't find the integration

### ISSUE THREAD

**Issue by AndreScalaPT** [DCSBL/ha-homewizard-energy#10]
I follow the instructions but the first step of "Usage" doesn't show the integration.
Tried to reboot several times and remove and add the repository and still don't appear.
I can see the folder in the custom components with Samba.

Thank you

**Comment by DCSBL** [comment]
Let's see, this can be causes by many things... Can you give some information that we can use to 'debug'?

- Can you give me some information about your environment? Like the HA version, how it is installed etc.
- What integration version do you have installed? And did you installed it manually or via HACS?
- Can you post a screenshot or exact description of the folder structure where you have copied?
- Can you see anything that is maybe related to this in the HA log?

Thank you ✌️

**Comment by AndreScalaPT** [comment]
Hi there,

I’ll try to give much information I can,

• Running Home Assistant 2021.1.5 in Raspberry PiRaspberry Pi 4 Model B 4 GB 32-bit;
• I added the HomeWizard Energy to Custom repositories in HACS (but there is that bug that appears there even without I added before)


	Logger: homeassistant.loader
	Source: loader.py:465
	First occurred: 14:25:44 (1 occurrences)
	Last logged: 14:25:44
	You are using a custom integration for homewizard_energy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

	Logger: homeassistant.components.webhook
	Source: components/webhook/__init__.py:84
	Integration: Webhook (documentation, issues)
	First occurred: 14:25:53 (1 occurrences)
	Last logged: 14:25:53
	Received message for unregistered webhook 7997ce592698da7ad285e8d0d4544339eb8440edeb414d5d465c90447c5ae867 from xx.xxx.xxx.xxx



Don’t know if helps with something.

Thank you,
Best regards,
Scala
Em 29/01/2021, 22:07 +0100, Duco Sebel <notifications@github.com>, escreveu:

**Comment by DCSBL** [comment]
That warning telling you are using a custom integrations tells me that HA _sees_ and loads the integration, so that's something!

Can you try to install the beta (0.5.0)? Should be an option in HACS. This version uses 'discovery' to find you device, maybe this will work.

**Comment by AndreScalaPT** [comment]
Hi,

Yes, with the new update now it appears ;D
Let’s see how’s the integration with InfluxDB and Grafana ;)

Great works!
Thanks
Em 30/01/2021, 15:02 +0100, Duco Sebel <notifications@github.com>, escreveu:
