### ISSUE TITLE
Custom Component losing connection to the P1 Meter

### ISSUE THREAD

**Issue by gcoupe** [DCSBL/ha-homewizard-energy#11]
The Home Assistant log has errors in the log of the form: 

Error requesting p1 meter data: Cannot connect to host 192.168.178.143:80 ssl:default [Connect call failed ('192.168.178.143', 80)]

These errors started being reported on the 29th January, but they may have been there earlier. We had a powercut that day, and so the logging could have started from scratch again.

The log summary states:

```
Logger: custom_components.homewizard_energy.sensor
Source: helpers/update_coordinator.py:153
Integration: HomeWizard Energy ([documentation](https://github.com/Unsigus/hass-homewizard-energy), [issues](https://github.com/Unsigus/hass-homewizard-energy/issues))
First occurred: 29 January 2021, 9:50:18 (89 occurrences)
Last logged: 11:30:25
Error requesting p1 meter data: Cannot connect to host 192.168.178.143:80 ssl:default [Connect call failed ('192.168.178.143', 80)]
```
They seem to be fairly random failures, perhaps 2 or 3 times per hour. Is this something to be looked at, or just ignore? Thanks.

The HomeWizard Energy app itself seems to be functioning as normal.

## System Health

version | 2021.1.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.79-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4950
Installed Version | 1.10.1
Stage | running
Available Repositories | 773
Installed Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.10
-- | --
update_channel | stable
supervisor_version | 2021.01.7
docker_version | 19.03.13
disk_total | 109.3 GB
disk_used | 10.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0), Samba share (9.3.0), Mosquitto broker (5.1), OpenZWave (0.9.0), Node-RED (8.0.1), InfluxDB (4.0.1), Terminal & SSH (8.10.0), Grafana (6.0.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
mode | auto-gen
resources | 8

</details>

**Comment by DCSBL** [comment]
Thank you for reporting!
I think you are using version v0.4? This version uses an 'old' method for fetching data. I think this should be solved with the release of v0.5.

If you are using HACS, you could try to install the beta version of 0.5. (You can select 'Reinstall' and then 'Show beta versions'.) You won't loose any data. If you do not use HACS or you don't trust updating, you can ignore the error for now.

Please let me know any results!

**Comment by gcoupe** [comment]
Hallo,

I can't seem to select the Beta version. I see it in the drop down menu, but when I try and select it in HACS, it seems to revert to version 0.4.3...

[cid:image001.png@01D6F807.D9F68680]

Is there a workaround? Thanks

Met vriendelijke groeten,

Geoff Coupe

http://gcoupe.wordpress.com/ - the Blog
http://flickr.com/photos/gcoupe - the Photos
https://cloud.collectorz.com/gcoupe/books  - the Library

**Comment by gcoupe** [comment]
OK, ignore the last message - I needed to first select an old version before the Beta version became available. Sorry for the trouble.

Met vriendelijke groeten,

Geoff Coupe

http://gcoupe.wordpress.com/ - the Blog
http://flickr.com/photos/gcoupe - the Photos
https://cloud.collectorz.com/gcoupe/books  - the Library

**Comment by DCSBL** [comment]
No worries! Great to see that you want to try!

**Comment by gcoupe** [comment]
Hmm,

I've restarted HA, but none of the P1 sensors are available anymore. Any thoughts? Thanks.

**Comment by DCSBL** [comment]
Is there anything to see in the log? Also, another restart has worked for me sometimes.

**Comment by gcoupe** [comment]
Yup - a second restart has brought everything back. Phew!

**Comment by DCSBL** [comment]
![Close call](https://media.giphy.com/media/xTkcEEuSayulok4IRq/giphy.gif)
---
All right! I will close this issue for now, please let me know if you get this, or another 'no connection' error back! Thanks for the quick replies!
