### ISSUE TITLE
Nieuwe tussenstukken api

### ISSUE THREAD

**Issue by peterjohan52** [DCSBL/ha-homewizard-energy#31]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Er is een nieuwe tussenstekker aangekondigd.
Wordt deze in de toekomst ook ondersteund?

**Comment by DCSBL** [comment]
Kort verhaal: Zeker!
Lang verhaal: Het meetgedeelte, zoals nu door de kWh en P1 meters gebruikt worden zal vrijwel gelijk zijn en waarschijnlijk direct werken met deze integratie. Over ondersteuning van andere functies kan ik nog niks kwijt.

**Comment by peterjohan52** [comment]
De api is gelijk aan de kWh meter. De data is exact gelijk.

**Comment by DCSBL** [comment]
De kWh meters zijn volledig ondersteund in deze integratie, als dat je vraag is.

**Comment by peterjohan52** [comment]
De smartplugs zijn nu in Beta. De api output is gelijk aan de 1 fase kWh meter.

**Comment by peterjohan52** [comment]
Als je herinstalleert, komen ze te voorschijn!
