### ISSUE TITLE
Support for the new Energy Management feature

### ISSUE THREAD

**Issue by Gerritjuuh** [DCSBL/ha-homewizard-energy#39]
**Is your feature request related to a problem? Please describe.**
Home assistant introduced the new Energy Management section. I think i would be awesome if this integration would support this so i could choose the correct attributes in this energy management wizard.

**Describe the solution you'd like**
Apparently the sensors need an extra attribute, see:
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by DCSBL** [comment]
Well, it _should_ have this already :). Please check if you have the expected behavior in

**Comment by Gerritjuuh** [comment]
Wow that's a quick reply :) And you are totally right. Was behind a few versions, my bad! 
Thanks for the great integration by the way 😄
