### ISSUE TITLE
Sensor for total kWh use

### ISSUE THREAD

**Issue by Legoracers** [DCSBL/ha-homewizard-energy#40]
**Is your feature request related to a problem? Please describe.**
In Home Assistant release 2021.8.0 the new energy dashboard was added. The dashboard asks for a entity that has the total power use as a value.

**Describe the solution you'd like**
I would like a sensor entity that adds sensor.p1_meter_total_power_import_t1 and sensor.p1_meter_total_power_import_t2 for a total power usage sensor.

**Describe alternatives you've considered**
I added a template sensor and added the 2 using jinja templating. It works for the value but the sensor can not be used in the energy dashboard.

**Comment by DCSBL** [comment]
Thank you for this request! Let's discuss some things.
1. It is not hard to add a 'total' field to this integration. But in my opinion it is up to Home Assistant to implement something to do templating without going into `configuration.yaml`. Even the official [DSMR integration](https://www.home-assistant.io/integrations/dsmr/) has no 'sum'. Even if I could, this implementation is not the place for such a feature don't you think?
2. The energy dashboard allows more than one source of totals. I added T1 *and* T2 to my config (see screenshot), and it works just fine. So maybe you don't even need this feature. Can you try to see if this is what you need?

<img width="606" alt="Schermafbeelding 2021-08-05 om 22 18 50" src="https://user-images.githubusercontent.com/74970928/128415594-966e1859-c504-427a-80da-0ca73d43f420.png">

**Comment by Legoracers** [comment]
I did not see the option to add a second consumption entity. This fixes the whole issue I have.
Thank you for creating the Energy Wizard integration and thank you for the quick response!

**Comment by DCSBL** [comment]
Awesome! Thanks for the update. Please let me know if you have other ideas of issues!
