### ISSUE TITLE
Entity names

### ISSUE THREAD

**Issue by klaasnicolaas** [DCSBL/ha-homewizard-energy#53]
**Is your feature request related to a problem? Please describe.**
The entities for import and export are named with power.

**Describe the solution you'd like**
Match the entity names with the unit of measurements and therefore an proposal to replace the word `power` for `energy` as power (Watt) and energy (kWh) are 2 different things.

**Comment by DCSBL** [comment]
Well, thanks! But have you checked out 0.10.0? :)

**Comment by DCSBL** [comment]
I’ve merged development into main. If i’ve done that before you already would have seen the change. Sorry for your time 🤭

**Comment by DCSBL** [comment]
_Removed my previous reaction as it was for the #52 PR._
Good idea, you are right.
