### ISSUE TITLE
P1 meter configuratie mislukt

### ISSUE THREAD

**Issue by TheGreatHorla** [DCSBL/ha-homewizard-energy#57]
Vandaag kwam ik tot de conclusie dat ik de entiteiten van de P1 meter niet meer zag in HA. Gisteren heb ik HA geüpdate naar de laatste versie, alles werkte maar in de loop van de nacht is hij dus gestopt. Ik heb daarjuist de integratie eens verwijderd en terug toegevoegd maar hij blijft op 'Instellen mislukt' staan. De HomeWizard app werkt nog dus de P1 meter zelf werkt nog zonder problemen.

Hoe zet ik debug aan? Ik heb homeassistant.components.homewizard: debug geprobeerd in mijn configuration file maar dat doet niets.

**Comment by DCSBL** [comment]
Debug zet je aan via:
```yaml
# configuration.yaml
logger:
  default: info
  logs:
    custom_components.homewizard_energy: debug
```

Als het goed is zou er in de logs iets te vinden moeten zijn waarom 'instellen mislukt' zou moeten zijn, zelfs zonder debug. Check wel even of je de volledige log bekijkt (`/config/logs` > "Load full Home Assistant Log").

Verder:
1.  Hoe heb je de integratie (opnieuw) geïnstalleerd (HACS/handmatig)?
2. Welke versie heb je geïnstalleerd? Dit is te zien in HACS of `<config_folder>/custom_components/homewizard_energy/manifest.json > version`
3. Heb je al gedacht aan simpele dingen zoals het opnieuw opstarten van Home Assistant?

**Comment by TheGreatHorla** [comment]
Alvast bedankt. Het ziet er echter naar uit dat het toch een probleem met de P1 meter is. http://{IP_ADDRESS}/api/v1/data in de browser geeft namelijk 'deze site is niet bereikbaar'.

**Comment by DCSBL** [comment]
Grote kans dat alles weer gaat werken als je de je P1 meter herstart. Als dit niet werkt kan je even contact opnemen met HomeWizard Support. Als er toch problemen zijn met de integratie kan je altijd hier weer reageren of een nieuwe issue openen.
