### ISSUE TITLE
Can't get any data.

### ISSUE THREAD

**Issue by St0kje** [DCSBL/ha-homewizard-energy#59]
**Describe the bug**

*A clear and concise description of what the bug is.*
After installing I can't get any data

**Environment (please complete the following information)**

Synology NAS 918 DSM7
 - Integration version: 0.10.0
 - Home Assistant version: Home Assistant 0.118.5
 - Python version (if known): 2.7.18-1004

**To Reproduce**

Eg. Steps to reproduce the behavior:
Installation went well, but nothing to select. 

**Expected behavior**

Energy reports and entities in HA. 

**Screenshots**

evt

**Log Output**

Logboekdetails (ERROR)

Logger: homeassistant.config_entries
Source: custom_components/homewizard_energy/__init__.py:172 
First occurred: 17:57:28 (2 occurrences) 
Last logged: 18:05:01

Error setting up entry P1 meter for homewizard_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/homewizard_energy/__init__.py", line 172, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
AttributeError: 'HWEnergyDeviceUpdateCoordinator' object has no attribute 'async_config_entry_first_refresh'

**Additional context**

**Comment by DCSBL** [comment]
You have HA 0.118.5 and Python 2.7. This integration is created for HA 2021.9 (and future versions). HA 2021.x supports only python 3.8 and 3.9.

I highly recommend you to upgrade your installation. I won't support issues with your outdated version. If you have any problems after upgrading, please don't hesitate to open a new issue.

**Comment by St0kje** [comment]
I understand.
I run it on my synology in Docker. Concening I have very little options. 

Thank you for your reply

**Comment by DCSBL** [comment]
Maybe you can install https://github.com/DCSBL/ha-homewizard-energy/releases/tag/0.4.3
It is a really old version but does not make use of the `UpdateCoordinator` that causes your issue. It should be available from HACS or install it through the ZIP attached with the release
