### ISSUE TITLE
Limited API Call when installing HACS. Therefore unable to pull HomeWizard

### ISSUE THREAD

**Issue by SmiCom** [DCSBL/ha-homewizard-energy#66]
Hello,

I am becoming a fan of the homewizard products but would like them to be integrated in HA.
Following your recommended option to download the integration via HACS I stubled upon the problem that HACS can't pull anything from GITHUB because of the call limitation. I have an authenticated (with token) account on github.

Error (in dutch, I'm from belgium): HACS is uitgeschakeld - Ratelimiet
GitHub API calls zijn gelimiteerd, dit zal over een uur weg zijn.

This is probably not a homewizard problem but since this is your prefered method of installation. You are probably aware of this. 
Could you point me in the right direction to get this solved or should I focus on the manual install? 

Regards, 
Sami

**Comment by DCSBL** [comment]
https://hacs.xyz/docs/faq/initial_startup

> For a new setups with HACS, with the current amount of default repositories you will hit that rate limit on the initial startup after downloading HACS. Because of this, HACS will be in a "Starting up" state until it's done fetching the information for all default repositories
> 
> Which in return will cause the initial startup of HACS to take over 1 hour to finish.

Just wait an hour or two.

**Comment by DCSBL** [comment]
You always can install the integration manually if you want to use it right now. HACS is just a fancy downloader/updater for custom integrations. If you install this integration manually and later use HACS, it will just work for future updates.

**Comment by SmiCom** [comment]
Fantastic! it works now (started yesterday). Thanks for the advice and keep up the good work!
