### ISSUE TITLE
Integration aborted

### ISSUE THREAD

**Issue by stefandj100** [DCSBL/ha-homewizard-energy#70]
Integratie toevoegen geeft de melding 'afgebroken' na het invoeren van de juiste IP.

 - Integration version: 12.1 (ook 11.0 geprobeerd)
 - Home Assistant version: 2021.12.7
 - Python version (if known): 3.9.7

Eg. Steps to reproduce the behavior:
1. Go to 'instellingen'
2. Click on 'add'
3. Scroll down to 'Home Wizard Energy'
4. See error Afgebroken

Integratie heeft maandenlang probleemloos gewerkt tot de entiteiten niet meer beschikbaar waren. Geprobeerd om de integratie opnieuw te installeren maar zonder resultaat. Uiteraard herstart ik HA na zulke acties.
http://192.168.2.25/api/v1/data geeft de juiste data weer en in de app ook.

Wat ik raar vind, is dat als ik via hacs de integratie verwijder en HA opnieuw opstart, ik nog steeds bij integraties kan zoeken naar Home wizard energy. Bij het verwijderen via hacs krijg ik ook de melding: De HomeWizard Energy -integratie is geconfigureerd, u moet de configuratie verwijderen voordat u deze uit HACS verwijdert.
Terwijl Home wizard niet meer tussen mijn lijst met ingestelde integraties staat.

Wat gaat hier niet goed? Hopelijk kan je helpen, want ik krijg de integratie niet meer werkend helaas.

**Comment by DCSBL** [comment]
Dit voelt aan als een situatie binnen jouw installatie en niet iets met de integratie zelf. De melding “afgebroken” zou waarschijnlijk moeten aangeven dat HomeWizard Energy al is ingesteld.

Probeer is bij de entities of devices te kijken of je iets kan verwijderen? Als dat lukt kan je is kijken of instellen weer lukt.

**Comment by stefandj100** [comment]
Hij werkt weer! Blijkbaar had ik de integratie uitgeschakeld waardoor ik deze melding kreeg. Als de integratie uitgeschakeld staat zie je hem niet meer. Toen de integratie even verwijderd en opnieuw toegevoegd. Hij werd netjes gevonden door HA en werkt weer mooi. Toch bedankt voor je reactie!
