### ISSUE TITLE
Add new options for display cost daily, month etc. 

### ISSUE THREAD

**Issue by snhnic** [DCSBL/ha-homewizard-energy#77]
Missing how to add display methods in Home Assistant. Were to find them for this new integration?

**Comment by DCSBL** [comment]
What do you mean? You maybe just want to  use https://www.home-assistant.io/docs/energy

**Comment by snhnic** [comment]
I mean in the add in the configuration.yaml 

template and utility_meter Since the meter has new name. Mine is now called  sensor.p1_meter_3c39e7251e82_active_power was sensor.p1_meter_active_power

**Comment by DCSBL** [comment]
You can rename the entity ID to whatever you want. Or update utility_meter sensor to what you need.

Your question is a bit unclear Is I mis some context. If you want any further help please fully describe your problem. This can be in Dutch if that is better for you.

**Comment by snhnic** [comment]
Sorry if it was not clear enough. I think you did a great job, but I'm missing new info on how to create costs display in the front end besides the energy dashboard. What to put in the configuration file to see a display with cost per month or whatever. No probs renaming, but as I said perhaps good to add it to the documentation with the integration
