### ISSUE TITLE
Changed URL 

### ISSUE THREAD

**Issue by Plaatjesdraaier** [DCSBL/ha-homewizard-energy#8]
Not really a bug, but the installation section refers to the wrong github.
Unfortunnately I had to delete the old integration in HACS and add the new url to use it.
Keep up the good work!

**Comment by DCSBL** [comment]
Thank you for reporting, have already fixed that!

But yes, I had to transfer this integration when I've merged my work and private GitHub accounts. GitHub redirects automatically redirects transferred repo's, but HACS does not handle that well...
