### ISSUE TITLE
Warnings since upgrade HA

### ISSUE THREAD

**Issue by gehob** [DCSBL/ha-homewizard-energy#80]
Several warnings appear since my upgrade to HA 2022.2.1:
all seam to have to do with the use of ' around properties.

 - Integration version: ? Last (updated, see no release number)
 - Home Assistant version: 2022.2.1
 - Python version (if known): 3.9.7

**To Reproduce**
Reboot, check logfile

**Expected behavior**
No warnings

*A clear and concise description of what you expected to happen.*
No warnings

*If applicable, add screenshots to help explain your problem.*

**Log Output**
The warnings:
Detected integration that accessed discovery_info['properties'] instead of discovery_info.properties; this will fail in version 2022.6. Please report issue to the custom component author for homewizard_energy using this method at custom_components/homewizard_energy/config_flow.py, line 135: if "product_name" in discovery_info["properties"]
Detected integration that accessed discovery_info['properties'] instead of discovery_info.properties; this will fail in version 2022.6. Please report issue to the custom component author for homewizard_energy using this method at custom_components/homewizard_energy/config_flow.py, line 138: if "product_type" in discovery_info["properties"]
Detected integration that accessed discovery_info['properties'] instead of discovery_info.properties; this will fail in version 2022.6. Please report issue to the custom component author for homewizard_energy using this method at custom_components/homewizard_energy/config_flow.py, line 137: "product_type": discovery_info["properties"]["product_type"]
Detected integration that accessed discovery_info['properties'] instead of discovery_info.properties; this will fail in version 2022.6. Please report issue to the custom component author for homewizard_energy using this method at custom_components/homewizard_energy/config_flow.py, line 141: if "serial" in discovery_info["properties"]
Detected integration that accessed discovery_info['properties'] instead of discovery_info.properties; this will fail in version 2022.6. Please report issue to the custom component author for homewizard_energy using this method at custom_components/homewizard_energy/config_flow.py, line 140: "serial": discovery_info["properties"]["serial"]
*If applicable*
To get more output, enable `debug` output
```yaml
# configuration.yaml
logger:
  default: info
  logs:
    custom_components.homewizard_energy: debug
```

**Additional context**

*Add any other context about the problem here.*

**Comment by DCSBL** [comment]
This has been solved in https://github.com/DCSBL/ha-homewizard-energy/pull/69. Try installing https://github.com/DCSBL/ha-homewizard-energy/releases/tag/0.12.1 and restart HA.

**Comment by gehob** [comment]
Thanks! Works. Upgrade did so to see not worked, now it has.

**Comment by DCSBL** [comment]
Goed om te horen! 👍
