### ISSUE TITLE
Warning: Data Migration from the HACS version to the Core version - Not possible today

### ISSUE THREAD

**Issue by adekloet** [DCSBL/ha-homewizard-energy#81]
Hi,

Since a lot of us like to have the history about our energy usage, especially in these times of very expensive energy, there must be a way to migrate data from the new domain created for Core from the older domain in HACS. Losing the data, means we lose insight on how we are doing compared to previous weeks and months. 

For now, I am using the new homewizard integration which works fine with slight differences. **If you don't delete the "obsolete" entities (HACS integration)** you can still graph those and use the data, although the energy config will complain about them (missing entities) missing in the active domain. 

It's workable (apart from the time the entities were double counting, due to the fact that I had both running).

I would suggest that the focus should be on migration. there must be a way to migrate old data in the database from the old domain to the new. (Maybe ask Frenck for some ideas on that)

It's a bummer like this.

To leave this message on a high note, I do appreciate all the hard work and effort and it made it into core. lucky people who start to work with it from today or don't care about history. 

All the best.

**Comment by DCSBL** [comment]
See https://github.com/DCSBL/ha-homewizard-energy/issues/74 and https://github.com/DCSBL/ha-homewizard-energy/pull/79

Just install Home Assistant 2022.2.2 (*or later) and https://github.com/DCSBL/ha-homewizard-energy/releases/tag/0.13.0. It will migrate the configuration and data to the core version.

**Comment by DCSBL** [comment]
O, and https://github.com/home-assistant/core/pull/65594

**Comment by adekloet** [comment]
No it won't work so easy.. I am already on 2.3, still lose history when I "remove" the HACS version.

**Comment by DCSBL** [comment]
Sorry, 2022.2.2 or later.

Make a backup, install 0.13.0, see what happens. It should all work out.

**Comment by adekloet** [comment]
yep did that, but again, I do lose history if I don't keep the "old entities alive" I see only data for the week in which the new integration is running. adding the old entities back in the energy config brings the data back in the UI. But having said that I am unable to find any log errors. 

More than an Issue this is more a heads up to others having issues that they are not alone, and that hopefully they save the other config and backed up. 

Thanks 

offcourse I did update HACS to the "migration version" 0.13.0 and the new integration was autodiscovered.

**Comment by adekloet** [comment]
![homewizard from old to new in a glance](https://user-images.githubusercontent.com/60182504/152819604-808e4174-f619-4555-8080-a0b670c307e6.png)
Feb 4: D-DAY
When HACS is removed I lose all visible FEB 3 and before
FEB 5: you see the double graphing, both integrations active (logical, both entities active and collecting)

FEB 7: disable HACS component but keep the old entities in the energy config to have them graphed in the UI, remove them the graphs become empty before feb 4. 

Re-added them, they are graphed again, although double counting during the Time of the overlap.
